### ISSUE TITLE
If creating the load-balancing robust server, update AWS python image

### ISSUE THREAD

**Issue by writezhe** [writezhe/transport-frictions-server#8]
In the wiki instructions, it reads:
> In the beiwe-backend repo, configure the file .elasticbeanstalk/config.yml:
```
branch-defaults:
  master:                            # You can change "master" to any branch name
    environment: [YOUR-ENV-NAME]
global:
  application_name: beiwe-application
  default_ec2_keyname: [DEPLOYMENT_KEY_NAME]  # Same as in global_configuration.json
  default_platform: 64bit Amazon Linux 2016.09 v2.3.0 running Python 2.7
  default_region: [AWS_REGION]                # Same as in global_configuration.json
  profile: eb-cli
  sc: git
```

The `default_platform` should be instead the most recent version, e.g. `64bit Amazon Linux 2017.09 v2.6.6 running Python 2.7`, otherwise, I've found it doesn't work.
